### ISSUE TITLE
Python 3 todo list

### ISSUE THREAD

**Issue by hayd** [pattern3/pattern#5]
I've broken up python 3 migration (#1) into the following independent tasks.
### Fix the (python 2) skipped tests see #3:
- [ ] mysql (this just needs travis to install it I think this is no big deal, i.e. just a line to .travis.yml)
- [ ] test command line (uses PIPE atm which doesn't work on py2.6)
- [ ] test _keywords
- [ ] skip MediaWikiArticle
- [ ] I think there is a couple more from #3 (search for FIXME and TODO)
### Python 3 stuff
- [x] print statements (#4)
- [x] get imports working from #4
- [ ] sgmllib is depreciated in python 3 (!) https://docs.python.org/2/library/sgmllib.html (I've kinda worked around this by renaming html.parser (which is a hack), the fact html.parser is in base may mean this section of pattern is no longer required https://github.com/clips/pattern/issues/4
- [ ] ... (triage remaining)
#### test files passing on python 3

e.g. via `nosetests test/test_xx.py`
- [x] add separate travis py3 build for the thus far passing tests
- [x] test_graph #11 
- [x] test_text en de... #16
- [x] test_metric 
- [ ] test_vector #17
- [ ] test_web
- [ ] test_db
- [ ] remove py3 special case build (once all the above are passing!)
### General stuff
- [x] use a single README (probably an rst is best)
- [x] add a MANIFEST.in - burn with fire the current os.walk stuff (other files?)
- [x] grab version number from the init file (rather than the pattern installation)
- [ ] style is a bit random for importing py3 stuff atm (my fault) should be more consistent
- [x] remove testing `suite` functions (just use `test_main`).
- [ ] some tests are pretty flaky (ie. numbers changing)
- [ ] remove utf-8 print hack added to the examples (due to `__future__ print_statement` being sensitive to unicode) i.e. make all the things unicode. See #12
- [ ] some tests are ombscurified by being so class based (although some which are still not very dry), atm I prefixed these with Abstract... but they should probably be ABC (the key is they can't start with Test otherwise nose etc tries to run them - and fails).
- [ ] javascript tests (?) currently not run - unclear if do they do anything?!
- [x] add examples to tests (e.g. have just run all the example py files, no assertions just running... but potentially could add some asserts?) - I nearly have done this.
- [ ] work out which dependancies can stop being vendorized (see below)
- [ ] depreciation messages of uses of dependancies (which have been updated), see travis/nose output
- [x] add travis, coveralls, landscape (sign up with pattern & pattern3 gh accounts and add this repo)
- [ ] add banner for the above into README
- [x] pep8/docformatter all the things (this should be simultaneously merged with clips/pattern, otherwise merging in work to clips will be very very difficult ???)
- [ ] **decide on when this can be merged back upstream** (IMO this should be asap, we don't require py3 to be ready just that py2 still works... and a quick pep8 storm :) )
### Performace
- [ ] come up with some benchmarks to compare python 2 and 3 (and potentially the old code base)
- [ ] profile and see what can be improved...

**Comment by EnricoGiampieri** [comment]
Hi, I'm interested in helping the port. I routinely work in python3 and I'm really interested in a "modern" version of this library. Any suggestion on where to start from?

**Comment by hayd** [comment]
@EnricoGiampieri I think getting `test_db.py` to run successfully is next up. Run the test and fix the errors/failures :)

**Comment by wannaphong** [comment]
fix sgmllib is depreciated in python 3 https://github.com/pattern3/pattern/pull/21

**Comment by maxschaf** [comment]
hi, there was no action in this repo during the last year. anyone still working on this?

**Comment by souravsingh** [comment]
Hi, I would like to contribute to the Project by fixing some skipped tests. How do I start?

**Comment by hayd** [comment]
@souravsingh see the comments in #3. larger projects are test_web and test_db.

#17 was waiting on @tom-de-smedt, so this port has stalled.

**Comment by james-see** [comment]
@hayd for mysql, I would just add in mysqlclient as a requirement, so in travis.yml add in install: pip3 install mysqlclient (or add it to requirements.txt) mysqlclient is a drop in replacement for MySQLdb and even imports the same way as import MySQLdb.

**Comment by james-see** [comment]
@hayd how best for me to do this part myself? fork and pull request it for that specific issue?

**Comment by JimSEOW** [comment]
As part of the process of running Gensim in py3.5 Win64 Windows10, I made a few changes to pattern3 
https://github.com/RaRe-Technologies/gensim/issues/1025

Update [1st Dec 2016]

@I git clone https://github.com/pattern3/pattern; python setup.py develop in MiniConda **py3.5 Win64**
=> First problem: pypiwin32
=> I downloaded [pypiwin32-219-cp35-none-win_amd64.whl](https://pypi.python.org/pypi/pypiwin32)
=> pip install pypiwin32-219-cp35-none-win_amd64.whl
=> repeat python setup.py develop with pattern3
=> Install works ok

FYI: I have not done all test yet!

![applicationframehost_2016-12-01_17-27-00](https://cloud.githubusercontent.com/assets/8244633/20802167/7020cc80-b7eb-11e6-879d-70e7651c037c.png)
![applicationframehost_2016-12-01_17-27-41](https://cloud.githubusercontent.com/assets/8244633/20802183/7dd5bd90-b7eb-11e6-833a-f7b29403a398.png)

**Comment by utkarshrai** [comment]
Is the project still on? I'd love to join in?

**Comment by city-in-the-sky** [comment]
Update: As part of Google Summer of Code 2017, Markus Beuckelmann (@markus-beuckelmann) will be working on the future of Pattern (porting it to Python 3 is first on our list). Markus is admin of the [main repo](https://github.com/clips/pattern) now and can handle pull requests and invite collaborators. Be sure to reach out to him and include him in discussions about the port. We'll focus on the main repo, and reintegrate what we can from the work done by @hayd here. Hopefully we can make some progress over the summer.
